site_name: Luwra
site_description: Minimal-overhead Lua wrapper for C++
repo_url: https://github.com/vapourismo/luwra
nav:
  - 'Home': index.md
  - 'Values': values.md
  - 'Stack Interaction': stack.md
  - 'State Wrapper': state.md
  - 'Utilities': utilities.md
  - 'Wrapping': wrapping.md
  - 'User Types': usertypes.md
theme: readthedocs
docs_dir: docs/mkdocs
site_dir: docs/output
